API - Ability to export Cisco UCCX configuration
Stack8/pbx-exporters pull request #2
Opened 2024-06-18 14:32 UTC by philippemin

2024-06-26 20:35 UTC, amonzerol requested changes

2024-06-26 20:35 UTC, amonzerol commented on ziro-export-uccx.ps1
> +    $allResources = $uccxConnector.InvokeGet('/adminapi/resource')
That variable is never used anywhere

2024-06-27 12:42 UTC, philippemin commented on ziro-export-uccx.ps1
> +    $allResources = $uccxConnector.InvokeGet('/adminapi/resource')
removed

2024-06-27 12:42 UTC, philippemin commented
@amonzerol ready for another pass

2024-06-27 14:11 UTC, amonzerol approved these changes

2024-06-27 14:47 UTC, merged